# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pr:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    echo "Running the sonar scanner"
    echo "completed the sonar scanner"
  displayName: 'review the code'  

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
- script: |
   npm audit || true
  displayName: 'npm security audit'
- script: |
    echo "Running the sonar scanner"
    echo "completed the sonar scanner"
  displayName: 'review the code'  
- script: 
   docker build -t jijopjoy80/order-managemgit nt:1.0 .
  displayName: 'docker' 

