apiVersion: v1
kind: Service
metadata:
  name: coit-frontend 
spec: 
  type: NodePort
  selector:
    app: coit-frontend
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
    
